In [ ]:
#Numpy (Numerical Python)
x = [1,2,3,4,5]
x_new = []
for z in x:
  x_new.append(z+1)
print(x_new)

[2, 3, 4, 5, 6]


In [ ]:
#Importing NUMPY library
import numpy as np #Alias name
x = [1,2,3,4,5]
#Coverting a list into an array
array1 = np.array(x)
#type(x)
#type(array1)
print(x)
x = [1,2,3,4,5]
x_new = []
for z in x:
  x_new.append(z+1)
print(x_new)

print(array1)
print(array1+1)
#An array, unlike a list, doesn't have the elements separated by commas

[1, 2, 3, 4, 5]
[2, 3, 4, 5, 6]
[1 2 3 4 5]
[2 3 4 5 6]


In [ ]:
import numpy as np
x = [1,2,3,4,5]
y = [6,7,8,9,10]
array1 = np.array(x)
array2 = np.array(y)
result_add = array1 + array2
print(result_add)
result_sub = array2 - array1
print(result_sub)
result_mul = array1 * array2
print(result_mul)

[ 7  9 11 13 15]
[5 5 5 5 5]
[ 6 14 24 36 50]


In [ ]:
import numpy as np
#Direct Conversion
array_1 = np.array([1,2,3,4,5])
array_2 = np.array([2,3,4,5,6])
max_val_1 = np.max(array_1)
max_val_2 = np.max(array_2)
min_val_1 = np.min(array_1)
min_val_2 = np.min(array_2)
print(min_val_2, min_val_1, max_val_1, max_val_2)
#Mean Value
np.mean(array_1)

2 1 5 6


3.0

In [ ]:
#Finding the dimension
x = [1,2,3,4,5]
import numpy as np
arr_x = np.array(x)
print(arr_x)
arr_x.ndim

[1 2 3 4 5]


1

In [ ]:
y = [[1,2,5],[3,4,6]]
import numpy as np
arr_y = np.array(y)
arr_y.ndim

2

In [ ]:
z = [[[1,2,3], [4,5,6]] , [[7,8,9], [10,11,12]]]
import numpy as np
arr_z = np.array(z)

'''
x = [] #step 1 Creating outermost list
x = [[],[]] #step 2 Creating inner list
x = [[[1,2,3], [4,5,6]] , [[7,8,9], [10,11,12]]] #step 3 Creating inner most list

'''
print(arr_z.ndim)
print(arr_z.shape)

3
(2, 2, 3)


In [ ]:
'''

array.shape
(x,y,z):
x => no. of outer list
y => no. of inner list
z => no. of values inside the inner list

'''

'\n\narray.shape\n(x,y,z):\nx => no. of outer list\ny => no. of inner list\nz => no. of values inside the inner list\n\n'

In [ ]:
import numpy as np
from numpy import random
x = (random.randint(100))
z = np.array(x)
z.ndim

0

## Array Generation

In [ ]:
x = random.randint(100, size=(5)) #1D Array
x.ndim

1

In [ ]:
y = random.randint(100, size=(2,5)) #2D Array
print(y)
print(y.ndim)

[[ 1 11 26 24 99]
 [95 81 78  0 23]]
2


In [ ]:
z = random.randint(100, size=(2,2,5)) #3D Array
print(z)
print(z.ndim)

[[[66 80 59 16 22]
  [59 78 84  3 82]]

 [[82 50  2 64 47]
  [21 74 95 81 69]]]
3


In [ ]:
#Arange (A-Range)
'''
Similar to range function, but this (A-Range) returns array

'''
print(np.arange(5))
print(np.arange(5, dtype = float))
print(np.arange(5, dtype = object)) #Handles/Supports (both float and integer) all data types

[0 1 2 3 4]
[0. 1. 2. 3. 4.]
[0 1 2 3 4]


In [ ]:
print(np.arange(5, 51, 5, dtype = object)) #Works as the range function in the form of an array

[5 10 15 20 25 30 35 40 45 50]


In [ ]:
#Write an arange
print(np.arange(50, 101, 10, dtype = object)) #Works as the range function in the form of an array

[50 60 70 80 90 100]


In [ ]:
print(np.zeros(7,dtype=float))
print(np.ones(7,dtype=float))
'''
Importance of this function: Used for computers help

'''

[0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1.]


'\nImportance of this function: Used for computers help\n\n'

In [ ]:
#Identity matrix: A matrix where the main diagonal elements are one and the rest are zeros
np.identity(4,dtype=object)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=object)

In [ ]:
import numpy as np
np.eye(4, k=-1, dtype=object) #K is the offset value which can be specified in the "eye" method

array([[0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]], dtype=object)

In [ ]:
orig = np.array([10,32,36,44,4,55])

#Converting 1D Array to 2D Array
print('Original Array ',orig)
#reshape
#Factors of the number of values in the array are the only numbers that can be used to specifiy things in the reshape function
reshaped = orig.reshape(3,2) #Number of lists and the number of values in each list is what the split up specifies
print('Reshaped Array\n',reshaped)

Original Array  [10 32 36 44  4 55]
Reshaped Array
 [[10 32]
 [36 44]
 [ 4 55]]


In [ ]:
lis = [34,5,6,2,4,99,10]
arr = np.array(lis)
rearr = arr.reshape(1,7)
print(rearr)
print(rearr.ndim)
rearr1 = arr.reshape(7,1)
print()
print(rearr1)
print(rearr1.ndim)

[[34  5  6  2  4 99 10]]
2

[[34]
 [ 5]
 [ 6]
 [ 2]
 [ 4]
 [99]
 [10]]
2


In [ ]:
liz = [1,2,3,4,5,6,7,8,9,10]
#Factors of 10 (number of values in liz): 5*2,2*5,1*10,10*1
lizz = np.array(liz)
reliz = lizz.reshape(5,2)
print(reliz)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [ ]:
#Converting 1D Array to 3D Array
l1 = [2,3,4,6,7,8,10,11,78,98,90,13]
arli = np.array(l1)
rearli = arli.reshape(3,2,2)
print(rearli)

[[[ 2  3]
  [ 4  6]]

 [[ 7  8]
  [10 11]]

 [[78 98]
  [90 13]]]


In [ ]:
l2 = [2,3,4,6,7,8,10,11,78,98,90,13,55,100]
ne_l2 = np.array(l2)
sh_new = ne_l2.reshape(1,7,2)
print(sh_new)

[[[  2   3]
  [  4   6]
  [  7   8]
  [ 10  11]
  [ 78  98]
  [ 90  13]
  [ 55 100]]]


In [ ]:
#Converting a 2D Array into 1D Array
l3 = [[22,23,24],[25,26,27]]
ar_l3 = np.array(l3)
rez = ar_l3.reshape(6,)
print(rez)

[22 23 24 25 26 27]


In [ ]:
#Converting a 3 D Array into 1D Array
l4 = [[[1,2,3],[8,9,10]],[[4,5,6],[11,12,13]]]
az = np.array(l4)
print('Original Dimension',az.ndim)
res = az.reshape(12,)
print('Reshaped Dimension',res.ndim)
print(res)

Original Dimension 3
Reshaped Dimension 1
[ 1  2  3  8  9 10  4  5  6 11 12 13]


In [ ]:
#Converting a 2D Array to a 3D Array
l3 = [[22,23,24],[25,26,27]]
arr_3 = np.array(l3)
print('Original Dimension',arr_3.ndim)
print(arr_3)
re_shaped = arr_3.reshape(3,2,1)
print('\nReshaped Dimension',re_shaped.ndim)
print(re_shaped)

Original Dimension 2
[[22 23 24]
 [25 26 27]]

Reshaped Dimension 3
[[[22]
  [23]]

 [[24]
  [25]]

 [[26]
  [27]]]


In [ ]:
#Reshaping 2*4 Array into 2*2*2 Array
ar = np.array([[10,32,34,56],[12,34,55,78]])
res_sh = ar.reshape(2,2,2)
print(res_sh)

[[[10 32]
  [34 56]]

 [[12 34]
  [55 78]]]


In [ ]:
#Reshaping 2*4 Array into 4D Array
ar = np.array([[10,32,34,56],[12,34,55,78]])
res_sh = ar.reshape(2,2,2,1)
print(res_sh)
print(res_sh.ndim)

[[[[10]
   [32]]

  [[34]
   [56]]]


 [[[12]
   [34]]

  [[55]
   [78]]]]
4


In [ ]:
#If the factor isn't known, then you can specify the number of arrays that you want and place -1 next to it after a comma, it does the reshaping on it's own
la = [[[1,2,3],[8,9,10]],[[4,5,6],[11,12,13]]]
azla = np.array(la)
resla = azla.reshape(3,-1)
print('Reshaped Dimension',resla.ndim)
print(resla)

Reshaped Dimension 2
[[ 1  2  3  8]
 [ 9 10  4  5]
 [ 6 11 12 13]]


In [ ]:
#Accessing Array Elements
'''
1) Slicing
2) Integer Array Indexing
3) Boolean Array Indexing
'''
import numpy as np
arrz = np.array([1,2,3,4,5,6])
arrz

array([1, 2, 3, 4, 5, 6])

In [ ]:
print('Array indexing: ',arrz[3])

Array indexing:  4


In [ ]:
arrz1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('Array Indexing: ',arrz1[1][1])
print('Array Slicing: ',arrz1[0:3,1]) #Gives the columns as the output
print('Array Slicing: ',arrz1[0:3,0]) #Gives the columns as the output
print(arrz1)

Array Indexing:  5
Array Slicing:  [2 5 8]
Array Slicing:  [1 4 7]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#Integer Array Indexing
arrz1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('Accessing value by integer value indexing: ',arrz1[[0,1,2],[0,1,2]])
print(arrz1) #The first box specifies the rows & the second specifies the columns, such that the column element is respective to the row


Accessing value by integer value indexing:  [1 5 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print('Accessing value by integer value indexing: ',arrz1[1,2])
print(arrz1) #The first box specifies the rows & the second specifies the columns, such that the column element is respective to the row

Accessing value by integer value indexing:  6
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#Boolean Array Indexing
arr3 = np.array( [[1,2,3,4],
        [5,6,7,8],
        [9,10,11,12]])
condition = arr3 > 10
print(condition)
print('Accessing the true values of the condition ',arr3[condition])

[[False False False False]
 [False False False False]
 [False False  True  True]]
Accessing the true values of the condition  [11 12]


In [ ]:
import numpy as np
students_array = np.array([['Student_1', 59, 64, 94, 87, 81],

                          ['Student_2', 8, 56, 18, 58, 69],

                          ['Student_3', 7, 20, 60, 63, 42],

                          ['Student_4', 71, 94, 71, 68, 13],

                          ['Student_5', 89, 1, 16, 33, 40],

                          ['Student_6', 4, 25, 48, 41, 84],

                          ['Student_7', 3, 79, 46, 9, 71],

                          ['Student_8', 87, 77, 75, 15, 69],

                          ['Student_9', 61, 1, 48, 98, 23],

                          ['Student_10', 98, 60, 24, 66, 56],

                          ['Student_11', 58, 12, 75, 7, 98],

                          ['Student_12', 23, 62, 6, 35, 37],

                          ['Student_13', 14, 25, 87, 56, 8],

                          ['Student_14', 68, 1, 81, 11, 61],


                          ['Student_15', 11, 69, 35, 17, 66]], dtype=object)

In [ ]:
#Accessing all the student names
print('The names of the students are ',students_array[:,0])

The names of the students are  ['Student_1' 'Student_2' 'Student_3' 'Student_4' 'Student_5' 'Student_6'
 'Student_7' 'Student_8' 'Student_9' 'Student_10' 'Student_11'
 'Student_12' 'Student_13' 'Student_14' 'Student_15']


In [ ]:
#Find the average of subject 1
sub_einen = students_array[:,1]
print(sub_einen)
sub_einen.mean()

[59 8 7 71 89 4 3 87 61 98 58 23 14 68 11]


44.06666666666667

In [ ]:
#Find the average of subject 2
sub_einen_1 = students_array[:,2]
print(sub_einen_1)
sub_einen_1.mean()

[64 56 20 94 1 25 79 77 1 60 12 62 25 1 69]


43.06666666666667

In [ ]:
#Find the average of student 4
stu = students_array[3,1:]
print(stu)
print(stu.mean())

[71 94 71 68 13]
63.4


In [ ]:
students_array[:,0]

array(['Student_1', 'Student_2', 'Student_3', 'Student_4', 'Student_5',
       'Student_6', 'Student_7', 'Student_8', 'Student_9', 'Student_10',
       'Student_11', 'Student_12', 'Student_13', 'Student_14',
       'Student_15'], dtype=object)

In [ ]:
#Find all student names where subject_1 marks is greater than subject_2
sub_1 = students_array[:,1]
sub_2 = students_array[:,2]

condition = sub_1 > sub_2

print("Total student count where subject_1 marks is greater than subject_2: ",condition.sum())

#Syntax to access array elements: var_name[rows,columns]

print("Names of students where subject_1 marks is greater than subject_2:\n",students_array[condition,:3])

Total student count where subject_1 marks is greater than subject_2:  6
Names of students where subject_1 marks is greater than subject_2:
 [['Student_5' 89 1]
 ['Student_8' 87 77]
 ['Student_9' 61 1]
 ['Student_10' 98 60]
 ['Student_11' 58 12]
 ['Student_14' 68 1]]


In [ ]:
stu_1 = students_array[0:10,1:]
print(stu_1)
print(stu_1.mean(axis = 1)) #Row wise average
print(stu_1.mean(axis = 0)) #Column wise average
#Mean parameter has an 'axis' parameter inside it: If axis = 0, then we get the mean column-wise else, we get mean row-wise

[[59 64 94 87 81]
 [8 56 18 58 69]
 [7 20 60 63 42]
 [71 94 71 68 13]
 [89 1 16 33 40]
 [4 25 48 41 84]
 [3 79 46 9 71]
 [87 77 75 15 69]
 [61 1 48 98 23]
 [98 60 24 66 56]]
[77.0 41.8 38.4 63.4 35.8 40.4 41.6 64.6 46.2 60.8]
[48.7 47.7 50.0 53.8 54.8]


In [ ]:
#Find the subject average of first 5 students
stu_2 = students_array[0:5,1:]
print(stu_2)
print('\nThe subject average of first 5 students is:  ',stu_2.mean(axis=1))

[[59 64 94 87 81]
 [8 56 18 58 69]
 [7 20 60 63 42]
 [71 94 71 68 13]
 [89 1 16 33 40]]

The subject average of first 5 students is:   [77.0 41.8 38.4 63.4 35.8]


In [ ]:
#Find the student average of students 5 to student 14
stu_3 = students_array[4:14,1:]
print(stu_3)
print('\nThe subject average of first 5 students upto student number 14th is:  ',stu_3.mean(axis=0))

[[89 1 16 33 40]
 [4 25 48 41 84]
 [3 79 46 9 71]
 [87 77 75 15 69]
 [61 1 48 98 23]
 [98 60 24 66 56]
 [58 12 75 7 98]
 [23 62 6 35 37]
 [14 25 87 56 8]
 [68 1 81 11 61]]

The subject average of first 5 students upto student number 14th is:   [50.5 34.3 50.6 37.1 54.7]


In [ ]:
#Find all the student names who scored higher than student_15 in both subject_1 and subject_2
sub_1 = students_array[:,1]
sub_2 = students_array[:,2]
student_15_sub1_marks = students_array[14,1]
student_15_sub2_marks = students_array[14,2]
condition_1 = sub_1 > student_15_sub1_marks
condition_2 = sub_2 > student_15_sub2_marks

merged_condition = (condition_1 & condition_2)

print('Student names that satisfy the condition: ',students_array[merged_condition])

Student names that satisfy the condition:  [['Student_4' 71 94 71 68 13]
 ['Student_8' 87 77 75 15 69]]


In [ ]:
#Find all the student names who scored higher than student_15 in either subject_1 or subject_2
sub_1 = students_array[:,1]
sub_2 = students_array[:,2]
student_15_sub1_marks = students_array[14,1]
student_15_sub2_marks = students_array[14,2]
condition_1 = sub_1 > student_15_sub1_marks
condition_2 = sub_2 > student_15_sub2_marks

merged_condition = (condition_1 | condition_2)

print('Student names that satisfy the condition: ',students_array[merged_condition,0])

Student names that satisfy the condition:  ['Student_1' 'Student_4' 'Student_5' 'Student_7' 'Student_8' 'Student_9'
 'Student_10' 'Student_11' 'Student_12' 'Student_13' 'Student_14']


In [ ]:
#Where condition in numpy
arrs = np.array([1,2,3,4,5])
cond = np.where(arrs > 2)
print(cond) #Gives the indices of the specific values
arrs[cond] #Gives the exact values

(array([2, 3, 4]),)


array([3, 4, 5])

In [ ]:
subj = students_array[:,1]
print("Marks greater than 50 ",np.where(subj>50))

Marks greater than 50  (array([ 0,  3,  4,  7,  8,  9, 10, 13]),)


In [ ]:
                        # Age, Employment Status, Marital Status, Balance, Personal Loan, Car Loan, Connection, Month of Joining
import numpy as np
banking_array = np.array([[30.0, 'unemployed', 'married', 1787.0, 'no', 'no', 'cellular','oct'],

       [33.0, 'services', 'married', 4789.0, 'yes', 'yes', 'cellular','may'],

       [35.0, 'management', 'single', 1350.0, 'yes', 'no', 'cellular','apr'],

       [30.0, 'management', 'married', 1476.0, 'yes', 'yes', 'unknown','jun'],

       [59.0, 'blue-collar', 'married', 0.0, 'yes', 'no', 'unknown','may'],

       [35.0, 'management', 'single', 747.0, 'no', 'no', 'cellular','feb'],

       [36.0, 'self-employed', 'married', 307.0, 'yes', 'no', 'cellular','may'],

       [39.0, 'technician', 'married', 147.0, 'yes', 'no', 'cellular','may'],

       [41.0, 'entrepreneur', 'married', 221.0, 'yes', 'no', 'unknown','may'],

       [43.0, 'services', 'married', -88.0, 'yes', 'yes', 'cellular','apr'],

       [39.0, 'services', 'married', 9374.0, 'yes', 'no', 'unknown','may'],

       [43.0, 'admin.', 'married', 264.0, 'yes', 'no', 'cellular', 'apr'],

       [36.0, 'technician', 'married', 1109.0, 'no', 'no', 'cellular','aug'],

       [20.0, 'student', 'single', 502.0, 'no', 'no', 'cellular', 'apr'],

       [31.0, 'blue-collar', 'married', 360.0, 'yes', 'yes', 'cellular','jan'],

       [40.0, 'management', 'married', 194.0, 'no', 'yes', 'cellular','aug'],

       [56.0, 'technician', 'married', 4073.0, 'no', 'no', 'cellular','aug'],

       [37.0, 'admin.', 'single', 2317.0, 'yes', 'no', 'cellular', 'apr'],

       [25.0, 'blue-collar', 'single', -221.0, 'yes', 'no', 'unknown','may'],

       [31.0, 'services', 'married', 132.0, 'no', 'no', 'cellular','jul']], dtype=object)

In [ ]:
#Finding the unique value from the DS
emp = banking_array[:,1]
cond = np.unique(emp)
cond

array(['admin.', 'blue-collar', 'entrepreneur', 'management',
       'self-employed', 'services', 'student', 'technician', 'unemployed'],
      dtype=object)

In [ ]:
#Find the customers who has taken a personal loan
loan = banking_array[:,4]
condi = (loan=='yes')
np.count_nonzero(condi)

13

In [ ]:
#Find the customers who has taken a car loan
cloan = banking_array[:,5]
c = (cloan=='yes')
np.count_nonzero(c)

5

In [ ]:
#Find the count of customers who have connection
connection = banking_array[:,6] #Or can be written as connection = banking_array[:,-2]
con = (connection=='cellular')
np.count_nonzero(con)

15

In [ ]:
#Find the count of customers who're married and has a personal loan
loan = banking_array[:,4]
mar = banking_array[:,2]
cons = (loan=='yes') & (mar=='married')
np.count_nonzero(cons)

10

In [ ]:
#Find the count of customers who have connection and has a car loan
connection = banking_array[:,6]
can = (connection=='cellular') & (cloan=='yes')
np.count_nonzero(can)

4

In [ ]:
#Find the count of customers whose age is greater than 25 and less than 40
age = banking_array[:,0]
condition = (age>25.0) & (age<40.0)
np.count_nonzero(condition)

12

In [ ]:
#Find the count of customers whose age is greater than 25 and less than 40, also find their bank balances and their sum total
age = banking_array[:,0]
condition = (age>25.0) & (age<40.0)
np.count_nonzero(condition)
bal = banking_array[:,3]
total = bal[condition]
print(total,'\n')
print('The total balance is',total.sum())

[1787.0 4789.0 1350.0 1476.0 747.0 307.0 147.0 9374.0 1109.0 360.0 2317.0
 132.0] 

The total balance is 23895.0


In [ ]:
#Find the count of customers whose age is greater than 25 and less than 40, also find their bank balances and their sum total
age = banking_array[:,0]
condition = (age>35.0) & (age<50.0)
np.count_nonzero(condition)
bal = banking_array[:,3]
total = bal[condition]
print(total,'\n')
print('The total balance is',total.sum())

[307.0 147.0 221.0 -88.0 9374.0 264.0 1109.0 194.0 2317.0] 

The total balance is 13845.0


In [ ]:
#Find the count of customers in management that're married and have a cellular connection
con1 = (banking_array[:,1]=='management')
con2 = (banking_array[:,2]=='married')
con3 = (banking_array[:,-2]=='cellular')

final_con = con1 & con2 & con3
np.count_nonzero(final_con)

1

In [ ]:
#Find the count of customers who're single and has a bank balance greater than average balance of customers
con4 = (banking_array[:,2]=='single')
avg = banking_array[:,3]
print(avg,'\n')
avg_bal = avg.mean()
print(avg_bal,'\n')
con5 = (banking_array[:,3]>avg_bal)
print(banking_array[con5],'\n')
#print(con5,'\n')
final = con4 & con5
np.count_nonzero(final)

[1787.0 4789.0 1350.0 1476.0 0.0 747.0 307.0 147.0 221.0 -88.0 9374.0
 264.0 1109.0 502.0 360.0 194.0 4073.0 2317.0 -221.0 132.0] 

1442.0 

[[30.0 'unemployed' 'married' 1787.0 'no' 'no' 'cellular' 'oct']
 [33.0 'services' 'married' 4789.0 'yes' 'yes' 'cellular' 'may']
 [30.0 'management' 'married' 1476.0 'yes' 'yes' 'unknown' 'jun']
 [39.0 'services' 'married' 9374.0 'yes' 'no' 'unknown' 'may']
 [56.0 'technician' 'married' 4073.0 'no' 'no' 'cellular' 'aug']
 [37.0 'admin.' 'single' 2317.0 'yes' 'no' 'cellular' 'apr']] 



1

In [ ]:
#Find people who're married and how many are single
mar = banking_array[:,2]
su = (mar=='married')
print('People who are married',su.sum())
suz = (mar=='single')
print('People who are single ',suz.sum())

People who are married 15
People who are single  5


In [ ]:
#Find people who're married and how many are single (easy & straightforward method)
mar = banking_array[:,2]
np.unique(mar, return_counts = True) #Gives us the count of the unique values in the array's rows/columns

(array(['married', 'single'], dtype=object), array([15,  5]))

In [ ]:
#Finding the people in various professions
prof = (banking_array[:,1])
np.unique(prof, return_counts = True)

(array(['admin.', 'blue-collar', 'entrepreneur', 'management',
        'self-employed', 'services', 'student', 'technician', 'unemployed'],
       dtype=object),
 array([2, 3, 1, 4, 1, 4, 1, 3, 1]))

In [ ]:
#Month that has the highest joining
month = banking_array[:,-1]
np.unique(month, return_counts = True)

(array(['apr', 'aug', 'feb', 'jan', 'jul', 'jun', 'may', 'oct'],
       dtype=object),
 array([5, 3, 1, 1, 1, 1, 7, 1]))

In [ ]:
#
age = (banking_array[:,0])
bal = (banking_array[:,3])
con = (age>=55) & (bal>2000)
filter = bal[con]
bonus = 0.05
inc = (bonus*filter) + filter
print(inc)

array([4276.65], dtype=object)

In [ ]:
age = (banking_array[:,0])
low = age<25
print(low)
high = age>25
print(high)
bal = (banking_array[:,3])
print(bal)
b_1=20000
b_2=10000
filter_1 = bal[low]
filter_2 = bal[high]
low_age = filter_1 + b_1
high_age = filter_2 + b_2
print(low_age)
print(high_age)

[False False False False False False False False False False False False
 False  True False False False False False False]
[ True  True  True  True  True  True  True  True  True  True  True  True
  True False  True  True  True  True False  True]
[1787.0 4789.0 1350.0 1476.0 0.0 747.0 307.0 147.0 221.0 -88.0 9374.0
 264.0 1109.0 502.0 360.0 194.0 4073.0 2317.0 -221.0 132.0]
[20502.0]
[11787.0 14789.0 11350.0 11476.0 10000.0 10747.0 10307.0 10147.0 10221.0
 9912.0 19374.0 10264.0 11109.0 10360.0 10194.0 14073.0 12317.0 10132.0]
